### ISSUE TITLE
Unable to create virtual displays on dGPUs that support hardware encoding

### ISSUE THREAD

**Issue by meisekiyou** [nomi-san/parsec-vdd#46]
My computer has two Graphics cards(iGPU & dGPU).
When I create a screen using parsec-vdd, the added virtual screen is connected to the iGPU.
I've tried disabling the iGPU, at which point the virtual screen created connects to the dGPU, but can't use the dGPU's hardware encoder.

**Comment by nomi-san** [comment]
I have implemented parent GPU selection, try the latest build in Actions: https://github.com/nomi-san/parsec-vdd/actions. Click Custom... -> Parent GPU -> Select your dGPU (NVIDIA or AMD), then restart your PC or just disable and enable the **Parsec Virtual Display Adapter** in Device Manager.

In additional, you can follow the official guide: https://support.parsec.app/hc/en-us/articles/4423615425293-VDD-Advanced-Configuration#parent_gpu

**Comment by meisekiyou** [comment]
Sorry,I didn't find the 'Parent GPU' option in version ParsecVDisplay-v0.45.2-6df9e867.

**Comment by nomi-san** [comment]
You should quit the running app first, then run this build, click Custom... -> Parent GPU.
Or follow this guide: https://support.parsec.app/hc/en-us/articles/4423615425293-VDD-Advanced-Configuration#parent_gpu

**Comment by meisekiyou** [comment]
Ok,i can see option now.But it not working.
I tried disable and enable the Parsec Virtual Display Adapter in Device Manager.It's still not working.
![20240622172656](https://github.com/nomi-san/parsec-vdd/assets/61874558/85252275-d0d8-43bc-bb61-95c2e95d3ce4)

**Comment by nomi-san** [comment]
It works, your display is set to extend or duplicate of DISPLAY1 (by iGPU).
For sure, just disable your iGPU.

**Comment by VwEl** [comment]
> It works, your display is set to extend or duplicate of DISPLAY1 (by iGPU). For sure, just disable your iGPU.

intel gpu how work？

**Comment by itsmikethetech** [comment]
Latest Beta HDR release includes this functionality. https://github.com/itsmikethetech/Virtual-Display-Driver/releases/tag/24.7.18HDR
